### ISSUE TITLE
Prepare Solidus Sitemap for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_sitemap#38]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by adammathys** [comment]
@derrickp and myself are going to pick this up.

**Comment by derrickp** [comment]
I've got this running locally and working on it now!

**Comment by seand7565** [comment]
Looks like this was closed by #39 🎉
